# Konfigurasi Air
root = "."
tmp_dir = "tmp"
[build]
  cmd = "go build -o tmp/main ."
  bin = "tmp/main"
  include_ext = ["go"]
  exclude_dir = ["vendor", "tmp", "migrations"]
  delay = 1000 # Delay restart dalam milidetik
  force_watch = false
  follow_symlink = false
